INSERT INTO GENDERS (NOMBRE) VALUES('MALE');
INSERT INTO GENDERS (NOMBRE) VALUES('FEMALE');


INSERT INTO JOBS (NOMBRE, SALARY) VALUES('DIRECTOR', 200000.10);
INSERT INTO JOBS (NOMBRE, SALARY) VALUES('GERENTE', 90000.10);
INSERT INTO JOBS (NOMBRE, SALARY) VALUES('SUPERVISOR', 45000.10);
INSERT INTO JOBS (NOMBRE, SALARY) VALUES('OBRERO', 20000.10);

INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, FIRST_NAME, LAST_NAME, BIRTHDAY) VALUES(1, 1, 'BRIAN', 'RIVERA', '1999-09-21');
INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, FIRST_NAME, LAST_NAME, BIRTHDAY) VALUES(1, 1, 'JUAN', 'PEREZ', '1999-09-21');
INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, FIRST_NAME, LAST_NAME, BIRTHDAY) VALUES(1, 3, 'PACO', 'GARCIA', '1999-09-21');
INSERT INTO EMPLOYEES (GENDER_ID, JOB_ID, FIRST_NAME, LAST_NAME, BIRTHDAY) VALUES(1, 4, 'PEDRO', 'HERNANDEZ', '1999-09-21');

INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(1, 7, '2024-01-07');
INSERT INTO EMPLOYEE_WORKED_HOURS (EMPLOYEE_ID, WORKED_HOURS, WORKED_DATE) VALUES(1, 7, '2024-01-08');







