CREATE TABLE IF NOT EXISTS GENDERS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS JOBS
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    SALARY DECIMAL(9, 2)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    GENDER_ID  BIGINT,
    JOB_ID     BIGINT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    BIRTHDAY   DATE,

    FOREIGN KEY (GENDER_ID) REFERENCES GENDERS (ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS (ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_WORKED_HOURS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID  BIGINT,
    WORKED_HOURS INT,
    WORKED_DATE  DATE,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);
